/********************************************************************************
** Form generated from reading UI file 'button_congee.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_BUTTON_CONGEE_H
#define UI_BUTTON_CONGEE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_button_congee
{
public:
    QTabWidget *tabWidget_3;
    QWidget *tab_8;
    QLineEdit *lineEdit_pc;
    QLineEdit *lineEdit_nc;
    QLineEdit *lineEdit_nbc;
    QPushButton *pushButton_7;
    QFrame *line_14;
    QFrame *line_15;
    QFrame *line_29;
    QFrame *line_30;
    QFrame *line_97;
    QFrame *line_98;
    QFrame *line_99;
    QFrame *line_100;
    QFrame *line_124;
    QFrame *line_125;
    QFrame *line_126;
    QFrame *line_127;
    QFrame *line_128;
    QFrame *line_129;
    QFrame *line_130;
    QFrame *line_131;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_39;
    QLabel *label_42;
    QPushButton *pushButton_15;
    QLabel *label_7;
    QLineEdit *lineEdit_27;
    QFrame *line_132;
    QLineEdit *lineEdit_vc;
    QFrame *line_133;
    QFrame *line_134;
    QLabel *label_43;
    QFrame *line_135;
    QLineEdit *lineEdit_idc;
    QFrame *line_136;
    QLabel *label_44;
    QFrame *line_137;
    QFrame *line_138;
    QLabel *label_3;
    QWidget *tab_9;
    QTableView *tableView_3;
    QLineEdit *lineEdit_nbm;
    QLineEdit *lineEdit_pm;
    QLineEdit *lineEdit_idm;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QFrame *line_139;
    QFrame *line_140;
    QFrame *line_141;
    QFrame *line_142;
    QFrame *line_143;
    QFrame *line_144;
    QFrame *line_145;
    QFrame *line_146;
    QFrame *line_147;
    QFrame *line_148;
    QFrame *line_149;
    QFrame *line_150;
    QFrame *line_151;
    QFrame *line_152;
    QFrame *line_153;
    QFrame *line_154;
    QFrame *line_155;
    QFrame *line_156;
    QFrame *line_157;
    QFrame *line_158;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QLineEdit *lineEdit_idmc;
    QPushButton *pushButton_18;
    QLabel *label_49;
    QLabel *label_4;
    QLabel *label_50;
    QFrame *line_159;
    QFrame *line_160;
    QFrame *line_161;
    QFrame *line_162;
    QLabel *label_51;
    QLabel *label_52;
    QFrame *line_163;
    QLabel *label_53;
    QLineEdit *lineEdit_nm;
    QFrame *line_164;
    QFrame *line_165;
    QFrame *line_166;
    QFrame *line_167;
    QFrame *line_168;
    QLabel *label_54;
    QFrame *line_169;
    QLineEdit *lineEdit_vm;
    QFrame *line_170;
    QWidget *tab_10;
    QFrame *line_171;
    QFrame *line_172;
    QTextEdit *msg_2;
    QLineEdit *rcpt_2;
    QLineEdit *file_2;
    QPushButton *sendBtn_2;
    QLineEdit *subject_2;
    QFrame *line_173;
    QLineEdit *mail_pass_2;
    QPushButton *browseBtn_2;
    QFrame *line_174;
    QFrame *line_175;

    void setupUi(QDialog *button_congee)
    {
        if (button_congee->objectName().isEmpty())
            button_congee->setObjectName(QStringLiteral("button_congee"));
        button_congee->resize(1068, 624);
        tabWidget_3 = new QTabWidget(button_congee);
        tabWidget_3->setObjectName(QStringLiteral("tabWidget_3"));
        tabWidget_3->setGeometry(QRect(0, 0, 1071, 631));
        tab_8 = new QWidget();
        tab_8->setObjectName(QStringLiteral("tab_8"));
        lineEdit_pc = new QLineEdit(tab_8);
        lineEdit_pc->setObjectName(QStringLiteral("lineEdit_pc"));
        lineEdit_pc->setGeometry(QRect(590, 150, 111, 31));
        QFont font;
        font.setFamily(QStringLiteral("Bahnschrift"));
        font.setPointSize(10);
        lineEdit_pc->setFont(font);
        lineEdit_nc = new QLineEdit(tab_8);
        lineEdit_nc->setObjectName(QStringLiteral("lineEdit_nc"));
        lineEdit_nc->setGeometry(QRect(340, 150, 121, 31));
        lineEdit_nc->setFont(font);
        lineEdit_nbc = new QLineEdit(tab_8);
        lineEdit_nbc->setObjectName(QStringLiteral("lineEdit_nbc"));
        lineEdit_nbc->setGeometry(QRect(150, 350, 121, 31));
        lineEdit_nbc->setFont(font);
        pushButton_7 = new QPushButton(tab_8);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(820, 260, 201, 81));
        QFont font1;
        font1.setFamily(QStringLiteral("Bahnschrift"));
        font1.setPointSize(16);
        pushButton_7->setFont(font1);
        line_14 = new QFrame(tab_8);
        line_14->setObjectName(QStringLiteral("line_14"));
        line_14->setGeometry(QRect(10, 500, 741, 20));
        line_14->setFrameShape(QFrame::HLine);
        line_14->setFrameShadow(QFrame::Sunken);
        line_15 = new QFrame(tab_8);
        line_15->setObjectName(QStringLiteral("line_15"));
        line_15->setGeometry(QRect(280, 30, 471, 20));
        line_15->setFrameShape(QFrame::HLine);
        line_15->setFrameShadow(QFrame::Sunken);
        line_29 = new QFrame(tab_8);
        line_29->setObjectName(QStringLiteral("line_29"));
        line_29->setGeometry(QRect(-7, 40, 20, 471));
        line_29->setFrameShape(QFrame::VLine);
        line_29->setFrameShadow(QFrame::Sunken);
        line_30 = new QFrame(tab_8);
        line_30->setObjectName(QStringLiteral("line_30"));
        line_30->setGeometry(QRect(740, 40, 20, 471));
        line_30->setFrameShape(QFrame::VLine);
        line_30->setFrameShadow(QFrame::Sunken);
        line_97 = new QFrame(tab_8);
        line_97->setObjectName(QStringLiteral("line_97"));
        line_97->setGeometry(QRect(140, 380, 141, 16));
        line_97->setFrameShape(QFrame::HLine);
        line_97->setFrameShadow(QFrame::Sunken);
        line_98 = new QFrame(tab_8);
        line_98->setObjectName(QStringLiteral("line_98"));
        line_98->setGeometry(QRect(250, 330, 31, 20));
        line_98->setFrameShape(QFrame::HLine);
        line_98->setFrameShadow(QFrame::Sunken);
        line_99 = new QFrame(tab_8);
        line_99->setObjectName(QStringLiteral("line_99"));
        line_99->setGeometry(QRect(330, 180, 141, 16));
        line_99->setFrameShape(QFrame::HLine);
        line_99->setFrameShadow(QFrame::Sunken);
        line_100 = new QFrame(tab_8);
        line_100->setObjectName(QStringLiteral("line_100"));
        line_100->setGeometry(QRect(440, 130, 31, 20));
        line_100->setFrameShape(QFrame::HLine);
        line_100->setFrameShadow(QFrame::Sunken);
        line_124 = new QFrame(tab_8);
        line_124->setObjectName(QStringLiteral("line_124"));
        line_124->setGeometry(QRect(670, 130, 31, 20));
        line_124->setFrameShape(QFrame::HLine);
        line_124->setFrameShadow(QFrame::Sunken);
        line_125 = new QFrame(tab_8);
        line_125->setObjectName(QStringLiteral("line_125"));
        line_125->setGeometry(QRect(580, 180, 131, 20));
        line_125->setFrameShape(QFrame::HLine);
        line_125->setFrameShadow(QFrame::Sunken);
        line_126 = new QFrame(tab_8);
        line_126->setObjectName(QStringLiteral("line_126"));
        line_126->setGeometry(QRect(130, 340, 20, 41));
        line_126->setFrameShape(QFrame::VLine);
        line_126->setFrameShadow(QFrame::Sunken);
        line_127 = new QFrame(tab_8);
        line_127->setObjectName(QStringLiteral("line_127"));
        line_127->setGeometry(QRect(270, 340, 20, 41));
        line_127->setFrameShape(QFrame::VLine);
        line_127->setFrameShadow(QFrame::Sunken);
        line_128 = new QFrame(tab_8);
        line_128->setObjectName(QStringLiteral("line_128"));
        line_128->setGeometry(QRect(320, 140, 20, 41));
        line_128->setFrameShape(QFrame::VLine);
        line_128->setFrameShadow(QFrame::Sunken);
        line_129 = new QFrame(tab_8);
        line_129->setObjectName(QStringLiteral("line_129"));
        line_129->setGeometry(QRect(460, 140, 20, 41));
        line_129->setFrameShape(QFrame::VLine);
        line_129->setFrameShadow(QFrame::Sunken);
        line_130 = new QFrame(tab_8);
        line_130->setObjectName(QStringLiteral("line_130"));
        line_130->setGeometry(QRect(700, 140, 20, 41));
        line_130->setFrameShape(QFrame::VLine);
        line_130->setFrameShadow(QFrame::Sunken);
        line_131 = new QFrame(tab_8);
        line_131->setObjectName(QStringLiteral("line_131"));
        line_131->setGeometry(QRect(570, 140, 20, 41));
        line_131->setFrameShape(QFrame::VLine);
        line_131->setFrameShadow(QFrame::Sunken);
        label_35 = new QLabel(tab_8);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(330, 122, 71, 21));
        label_35->setFont(font1);
        label_36 = new QLabel(tab_8);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(130, 300, 151, 31));
        label_36->setFont(font1);
        label_39 = new QLabel(tab_8);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(580, 110, 111, 31));
        label_39->setFont(font1);
        label_42 = new QLabel(tab_8);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(780, 260, 71, 71));
        pushButton_15 = new QPushButton(tab_8);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(60, 10, 211, 81));
        QFont font2;
        font2.setFamily(QStringLiteral("Bahnschrift"));
        font2.setPointSize(20);
        pushButton_15->setFont(font2);
        label_7 = new QLabel(tab_8);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(20, 10, 71, 71));
        lineEdit_27 = new QLineEdit(tab_8);
        lineEdit_27->setObjectName(QStringLiteral("lineEdit_27"));
        lineEdit_27->setGeometry(QRect(840, 460, 141, 41));
        lineEdit_27->setFont(font2);
        line_132 = new QFrame(tab_8);
        line_132->setObjectName(QStringLiteral("line_132"));
        line_132->setGeometry(QRect(410, 380, 131, 20));
        line_132->setFrameShape(QFrame::HLine);
        line_132->setFrameShadow(QFrame::Sunken);
        lineEdit_vc = new QLineEdit(tab_8);
        lineEdit_vc->setObjectName(QStringLiteral("lineEdit_vc"));
        lineEdit_vc->setGeometry(QRect(420, 350, 111, 31));
        lineEdit_vc->setFont(font);
        line_133 = new QFrame(tab_8);
        line_133->setObjectName(QStringLiteral("line_133"));
        line_133->setGeometry(QRect(540, 340, 20, 41));
        line_133->setFrameShape(QFrame::VLine);
        line_133->setFrameShadow(QFrame::Sunken);
        line_134 = new QFrame(tab_8);
        line_134->setObjectName(QStringLiteral("line_134"));
        line_134->setGeometry(QRect(400, 340, 20, 41));
        line_134->setFrameShape(QFrame::VLine);
        line_134->setFrameShadow(QFrame::Sunken);
        label_43 = new QLabel(tab_8);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(390, 300, 231, 31));
        label_43->setFont(font1);
        line_135 = new QFrame(tab_8);
        line_135->setObjectName(QStringLiteral("line_135"));
        line_135->setGeometry(QRect(220, 140, 20, 41));
        line_135->setFrameShape(QFrame::VLine);
        line_135->setFrameShadow(QFrame::Sunken);
        lineEdit_idc = new QLineEdit(tab_8);
        lineEdit_idc->setObjectName(QStringLiteral("lineEdit_idc"));
        lineEdit_idc->setGeometry(QRect(100, 150, 121, 31));
        lineEdit_idc->setFont(font);
        line_136 = new QFrame(tab_8);
        line_136->setObjectName(QStringLiteral("line_136"));
        line_136->setGeometry(QRect(80, 140, 20, 41));
        line_136->setFrameShape(QFrame::VLine);
        line_136->setFrameShadow(QFrame::Sunken);
        label_44 = new QLabel(tab_8);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(90, 122, 71, 21));
        label_44->setFont(font1);
        line_137 = new QFrame(tab_8);
        line_137->setObjectName(QStringLiteral("line_137"));
        line_137->setGeometry(QRect(90, 180, 141, 16));
        line_137->setFrameShape(QFrame::HLine);
        line_137->setFrameShadow(QFrame::Sunken);
        line_138 = new QFrame(tab_8);
        line_138->setObjectName(QStringLiteral("line_138"));
        line_138->setGeometry(QRect(200, 130, 31, 20));
        line_138->setFrameShape(QFrame::HLine);
        line_138->setFrameShadow(QFrame::Sunken);
        label_3 = new QLabel(tab_8);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(20, -60, 1051, 861));
        tabWidget_3->addTab(tab_8, QString());
        label_3->raise();
        lineEdit_pc->raise();
        lineEdit_nc->raise();
        lineEdit_nbc->raise();
        pushButton_7->raise();
        line_14->raise();
        line_15->raise();
        line_29->raise();
        line_30->raise();
        line_97->raise();
        line_98->raise();
        line_99->raise();
        line_100->raise();
        line_124->raise();
        line_125->raise();
        line_126->raise();
        line_127->raise();
        line_128->raise();
        line_129->raise();
        line_130->raise();
        line_131->raise();
        label_35->raise();
        label_36->raise();
        label_39->raise();
        label_42->raise();
        pushButton_15->raise();
        label_7->raise();
        lineEdit_27->raise();
        line_132->raise();
        lineEdit_vc->raise();
        line_133->raise();
        line_134->raise();
        label_43->raise();
        line_135->raise();
        lineEdit_idc->raise();
        line_136->raise();
        label_44->raise();
        line_137->raise();
        line_138->raise();
        tab_9 = new QWidget();
        tab_9->setObjectName(QStringLiteral("tab_9"));
        tableView_3 = new QTableView(tab_9);
        tableView_3->setObjectName(QStringLiteral("tableView_3"));
        tableView_3->setGeometry(QRect(650, 180, 311, 271));
        lineEdit_nbm = new QLineEdit(tab_9);
        lineEdit_nbm->setObjectName(QStringLiteral("lineEdit_nbm"));
        lineEdit_nbm->setGeometry(QRect(290, 220, 121, 31));
        lineEdit_nbm->setFont(font);
        lineEdit_pm = new QLineEdit(tab_9);
        lineEdit_pm->setObjectName(QStringLiteral("lineEdit_pm"));
        lineEdit_pm->setGeometry(QRect(50, 220, 121, 31));
        lineEdit_pm->setFont(font);
        lineEdit_idm = new QLineEdit(tab_9);
        lineEdit_idm->setObjectName(QStringLiteral("lineEdit_idm"));
        lineEdit_idm->setGeometry(QRect(50, 130, 121, 31));
        lineEdit_idm->setFont(font);
        pushButton_8 = new QPushButton(tab_9);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(320, 300, 211, 81));
        QFont font3;
        font3.setFamily(QStringLiteral("Bahnschrift"));
        font3.setPointSize(14);
        pushButton_8->setFont(font3);
        pushButton_9 = new QPushButton(tab_9);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(320, 410, 211, 81));
        pushButton_9->setFont(font3);
        line_139 = new QFrame(tab_9);
        line_139->setObjectName(QStringLiteral("line_139"));
        line_139->setGeometry(QRect(40, 160, 141, 16));
        line_139->setFrameShape(QFrame::HLine);
        line_139->setFrameShadow(QFrame::Sunken);
        line_140 = new QFrame(tab_9);
        line_140->setObjectName(QStringLiteral("line_140"));
        line_140->setGeometry(QRect(150, 290, 31, 20));
        line_140->setFrameShape(QFrame::HLine);
        line_140->setFrameShadow(QFrame::Sunken);
        line_141 = new QFrame(tab_9);
        line_141->setObjectName(QStringLiteral("line_141"));
        line_141->setGeometry(QRect(150, 110, 31, 20));
        line_141->setFrameShape(QFrame::HLine);
        line_141->setFrameShadow(QFrame::Sunken);
        line_142 = new QFrame(tab_9);
        line_142->setObjectName(QStringLiteral("line_142"));
        line_142->setGeometry(QRect(390, 110, 31, 20));
        line_142->setFrameShape(QFrame::HLine);
        line_142->setFrameShadow(QFrame::Sunken);
        line_143 = new QFrame(tab_9);
        line_143->setObjectName(QStringLiteral("line_143"));
        line_143->setGeometry(QRect(280, 160, 141, 16));
        line_143->setFrameShape(QFrame::HLine);
        line_143->setFrameShadow(QFrame::Sunken);
        line_144 = new QFrame(tab_9);
        line_144->setObjectName(QStringLiteral("line_144"));
        line_144->setGeometry(QRect(40, 340, 141, 16));
        line_144->setFrameShape(QFrame::HLine);
        line_144->setFrameShadow(QFrame::Sunken);
        line_145 = new QFrame(tab_9);
        line_145->setObjectName(QStringLiteral("line_145"));
        line_145->setGeometry(QRect(30, 120, 20, 41));
        line_145->setFrameShape(QFrame::VLine);
        line_145->setFrameShadow(QFrame::Sunken);
        line_146 = new QFrame(tab_9);
        line_146->setObjectName(QStringLiteral("line_146"));
        line_146->setGeometry(QRect(170, 120, 20, 41));
        line_146->setFrameShape(QFrame::VLine);
        line_146->setFrameShadow(QFrame::Sunken);
        line_147 = new QFrame(tab_9);
        line_147->setObjectName(QStringLiteral("line_147"));
        line_147->setGeometry(QRect(170, 300, 20, 41));
        line_147->setFrameShape(QFrame::VLine);
        line_147->setFrameShadow(QFrame::Sunken);
        line_148 = new QFrame(tab_9);
        line_148->setObjectName(QStringLiteral("line_148"));
        line_148->setGeometry(QRect(30, 300, 20, 41));
        line_148->setFrameShape(QFrame::VLine);
        line_148->setFrameShadow(QFrame::Sunken);
        line_149 = new QFrame(tab_9);
        line_149->setObjectName(QStringLiteral("line_149"));
        line_149->setGeometry(QRect(270, 120, 20, 41));
        line_149->setFrameShape(QFrame::VLine);
        line_149->setFrameShadow(QFrame::Sunken);
        line_150 = new QFrame(tab_9);
        line_150->setObjectName(QStringLiteral("line_150"));
        line_150->setGeometry(QRect(410, 120, 20, 41));
        line_150->setFrameShape(QFrame::VLine);
        line_150->setFrameShadow(QFrame::Sunken);
        line_151 = new QFrame(tab_9);
        line_151->setObjectName(QStringLiteral("line_151"));
        line_151->setGeometry(QRect(10, 50, 20, 491));
        line_151->setFrameShape(QFrame::VLine);
        line_151->setFrameShadow(QFrame::Sunken);
        line_152 = new QFrame(tab_9);
        line_152->setObjectName(QStringLiteral("line_152"));
        line_152->setGeometry(QRect(560, 50, 20, 491));
        line_152->setFrameShape(QFrame::VLine);
        line_152->setFrameShadow(QFrame::Sunken);
        line_153 = new QFrame(tab_9);
        line_153->setObjectName(QStringLiteral("line_153"));
        line_153->setGeometry(QRect(20, 540, 551, 16));
        line_153->setFrameShape(QFrame::HLine);
        line_153->setFrameShadow(QFrame::Sunken);
        line_154 = new QFrame(tab_9);
        line_154->setObjectName(QStringLiteral("line_154"));
        line_154->setGeometry(QRect(290, 40, 281, 20));
        line_154->setFrameShape(QFrame::HLine);
        line_154->setFrameShadow(QFrame::Sunken);
        line_155 = new QFrame(tab_9);
        line_155->setObjectName(QStringLiteral("line_155"));
        line_155->setGeometry(QRect(640, 450, 331, 20));
        line_155->setFrameShape(QFrame::HLine);
        line_155->setFrameShadow(QFrame::Sunken);
        line_156 = new QFrame(tab_9);
        line_156->setObjectName(QStringLiteral("line_156"));
        line_156->setGeometry(QRect(630, 170, 20, 291));
        line_156->setFrameShape(QFrame::VLine);
        line_156->setFrameShadow(QFrame::Sunken);
        line_157 = new QFrame(tab_9);
        line_157->setObjectName(QStringLiteral("line_157"));
        line_157->setGeometry(QRect(640, 160, 331, 20));
        line_157->setFrameShape(QFrame::HLine);
        line_157->setFrameShadow(QFrame::Sunken);
        line_158 = new QFrame(tab_9);
        line_158->setObjectName(QStringLiteral("line_158"));
        line_158->setGeometry(QRect(960, 170, 21, 291));
        line_158->setFrameShape(QFrame::VLine);
        line_158->setFrameShadow(QFrame::Sunken);
        label_45 = new QLabel(tab_9);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(40, 100, 71, 21));
        label_45->setFont(font1);
        label_46 = new QLabel(tab_9);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(20, 270, 201, 21));
        label_46->setFont(font1);
        label_47 = new QLabel(tab_9);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(280, 100, 111, 21));
        label_47->setFont(font1);
        pushButton_16 = new QPushButton(tab_9);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(740, 490, 131, 51));
        pushButton_16->setFont(font);
        pushButton_17 = new QPushButton(tab_9);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(860, 50, 171, 61));
        QFont font4;
        font4.setFamily(QStringLiteral("Bahnschrift"));
        font4.setPointSize(7);
        pushButton_17->setFont(font4);
        lineEdit_idmc = new QLineEdit(tab_9);
        lineEdit_idmc->setObjectName(QStringLiteral("lineEdit_idmc"));
        lineEdit_idmc->setGeometry(QRect(690, 70, 111, 31));
        lineEdit_idmc->setFont(font);
        pushButton_18 = new QPushButton(tab_9);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(80, 10, 211, 81));
        pushButton_18->setFont(font2);
        label_49 = new QLabel(tab_9);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(40, 10, 71, 71));
        label_4 = new QLabel(tab_9);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(0, -20, 1061, 541));
        label_50 = new QLabel(tab_9);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(280, 410, 71, 71));
        line_159 = new QFrame(tab_9);
        line_159->setObjectName(QStringLiteral("line_159"));
        line_159->setGeometry(QRect(680, 100, 131, 16));
        line_159->setFrameShape(QFrame::HLine);
        line_159->setFrameShadow(QFrame::Sunken);
        line_160 = new QFrame(tab_9);
        line_160->setObjectName(QStringLiteral("line_160"));
        line_160->setGeometry(QRect(770, 50, 41, 20));
        line_160->setFrameShape(QFrame::HLine);
        line_160->setFrameShadow(QFrame::Sunken);
        line_161 = new QFrame(tab_9);
        line_161->setObjectName(QStringLiteral("line_161"));
        line_161->setGeometry(QRect(670, 60, 20, 41));
        line_161->setFrameShape(QFrame::VLine);
        line_161->setFrameShadow(QFrame::Sunken);
        line_162 = new QFrame(tab_9);
        line_162->setObjectName(QStringLiteral("line_162"));
        line_162->setGeometry(QRect(800, 60, 20, 51));
        line_162->setFrameShape(QFrame::VLine);
        line_162->setFrameShadow(QFrame::Sunken);
        label_51 = new QLabel(tab_9);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(680, 40, 111, 21));
        label_51->setFont(font1);
        label_52 = new QLabel(tab_9);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(810, 60, 51, 51));
        line_163 = new QFrame(tab_9);
        line_163->setObjectName(QStringLiteral("line_163"));
        line_163->setGeometry(QRect(40, 250, 141, 16));
        line_163->setFrameShape(QFrame::HLine);
        line_163->setFrameShadow(QFrame::Sunken);
        label_53 = new QLabel(tab_9);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(40, 190, 71, 21));
        label_53->setFont(font1);
        lineEdit_nm = new QLineEdit(tab_9);
        lineEdit_nm->setObjectName(QStringLiteral("lineEdit_nm"));
        lineEdit_nm->setGeometry(QRect(290, 130, 121, 31));
        lineEdit_nm->setFont(font);
        line_164 = new QFrame(tab_9);
        line_164->setObjectName(QStringLiteral("line_164"));
        line_164->setGeometry(QRect(170, 210, 20, 41));
        line_164->setFrameShape(QFrame::VLine);
        line_164->setFrameShadow(QFrame::Sunken);
        line_165 = new QFrame(tab_9);
        line_165->setObjectName(QStringLiteral("line_165"));
        line_165->setGeometry(QRect(30, 210, 20, 41));
        line_165->setFrameShape(QFrame::VLine);
        line_165->setFrameShadow(QFrame::Sunken);
        line_166 = new QFrame(tab_9);
        line_166->setObjectName(QStringLiteral("line_166"));
        line_166->setGeometry(QRect(150, 200, 31, 20));
        line_166->setFrameShape(QFrame::HLine);
        line_166->setFrameShadow(QFrame::Sunken);
        line_167 = new QFrame(tab_9);
        line_167->setObjectName(QStringLiteral("line_167"));
        line_167->setGeometry(QRect(410, 210, 20, 41));
        line_167->setFrameShape(QFrame::VLine);
        line_167->setFrameShadow(QFrame::Sunken);
        line_168 = new QFrame(tab_9);
        line_168->setObjectName(QStringLiteral("line_168"));
        line_168->setGeometry(QRect(280, 250, 141, 16));
        line_168->setFrameShape(QFrame::HLine);
        line_168->setFrameShadow(QFrame::Sunken);
        label_54 = new QLabel(tab_9);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(270, 180, 161, 21));
        label_54->setFont(font1);
        line_169 = new QFrame(tab_9);
        line_169->setObjectName(QStringLiteral("line_169"));
        line_169->setGeometry(QRect(270, 210, 20, 41));
        line_169->setFrameShape(QFrame::VLine);
        line_169->setFrameShadow(QFrame::Sunken);
        lineEdit_vm = new QLineEdit(tab_9);
        lineEdit_vm->setObjectName(QStringLiteral("lineEdit_vm"));
        lineEdit_vm->setGeometry(QRect(50, 310, 121, 31));
        lineEdit_vm->setFont(font);
        line_170 = new QFrame(tab_9);
        line_170->setObjectName(QStringLiteral("line_170"));
        line_170->setGeometry(QRect(390, 200, 31, 20));
        line_170->setFrameShape(QFrame::HLine);
        line_170->setFrameShadow(QFrame::Sunken);
        tabWidget_3->addTab(tab_9, QString());
        label_4->raise();
        tableView_3->raise();
        lineEdit_nbm->raise();
        lineEdit_pm->raise();
        lineEdit_idm->raise();
        pushButton_8->raise();
        pushButton_9->raise();
        line_139->raise();
        line_140->raise();
        line_141->raise();
        line_142->raise();
        line_143->raise();
        line_144->raise();
        line_145->raise();
        line_146->raise();
        line_147->raise();
        line_148->raise();
        line_149->raise();
        line_150->raise();
        line_151->raise();
        line_152->raise();
        line_153->raise();
        line_154->raise();
        line_155->raise();
        line_156->raise();
        line_157->raise();
        line_158->raise();
        label_45->raise();
        label_46->raise();
        label_47->raise();
        pushButton_16->raise();
        pushButton_17->raise();
        lineEdit_idmc->raise();
        pushButton_18->raise();
        label_49->raise();
        label_50->raise();
        line_159->raise();
        line_160->raise();
        line_161->raise();
        line_162->raise();
        label_51->raise();
        label_52->raise();
        line_163->raise();
        label_53->raise();
        lineEdit_nm->raise();
        line_164->raise();
        line_165->raise();
        line_166->raise();
        line_167->raise();
        line_168->raise();
        label_54->raise();
        line_169->raise();
        lineEdit_vm->raise();
        line_170->raise();
        tab_10 = new QWidget();
        tab_10->setObjectName(QStringLiteral("tab_10"));
        line_171 = new QFrame(tab_10);
        line_171->setObjectName(QStringLiteral("line_171"));
        line_171->setGeometry(QRect(880, 20, 20, 501));
        line_171->setFrameShape(QFrame::VLine);
        line_171->setFrameShadow(QFrame::Sunken);
        line_172 = new QFrame(tab_10);
        line_172->setObjectName(QStringLiteral("line_172"));
        line_172->setGeometry(QRect(110, 10, 771, 20));
        line_172->setFrameShape(QFrame::HLine);
        line_172->setFrameShadow(QFrame::Sunken);
        msg_2 = new QTextEdit(tab_10);
        msg_2->setObjectName(QStringLiteral("msg_2"));
        msg_2->setGeometry(QRect(200, 180, 651, 291));
        rcpt_2 = new QLineEdit(tab_10);
        rcpt_2->setObjectName(QStringLiteral("rcpt_2"));
        rcpt_2->setGeometry(QRect(200, 40, 491, 21));
        file_2 = new QLineEdit(tab_10);
        file_2->setObjectName(QStringLiteral("file_2"));
        file_2->setGeometry(QRect(200, 120, 571, 23));
        sendBtn_2 = new QPushButton(tab_10);
        sendBtn_2->setObjectName(QStringLiteral("sendBtn_2"));
        sendBtn_2->setGeometry(QRect(200, 470, 651, 51));
        subject_2 = new QLineEdit(tab_10);
        subject_2->setObjectName(QStringLiteral("subject_2"));
        subject_2->setGeometry(QRect(200, 80, 651, 16));
        line_173 = new QFrame(tab_10);
        line_173->setObjectName(QStringLiteral("line_173"));
        line_173->setGeometry(QRect(70, 30, 20, 491));
        line_173->setFrameShape(QFrame::VLine);
        line_173->setFrameShadow(QFrame::Sunken);
        mail_pass_2 = new QLineEdit(tab_10);
        mail_pass_2->setObjectName(QStringLiteral("mail_pass_2"));
        mail_pass_2->setGeometry(QRect(710, 40, 141, 20));
        mail_pass_2->setEchoMode(QLineEdit::Password);
        browseBtn_2 = new QPushButton(tab_10);
        browseBtn_2->setObjectName(QStringLiteral("browseBtn_2"));
        browseBtn_2->setGeometry(QRect(770, 110, 111, 41));
        line_174 = new QFrame(tab_10);
        line_174->setObjectName(QStringLiteral("line_174"));
        line_174->setGeometry(QRect(140, 520, 681, 16));
        line_174->setFrameShape(QFrame::HLine);
        line_174->setFrameShadow(QFrame::Sunken);
        tabWidget_3->addTab(tab_10, QString());
        line_175 = new QFrame(button_congee);
        line_175->setObjectName(QStringLiteral("line_175"));
        line_175->setGeometry(QRect(1760, 580, 20, 501));
        line_175->setFrameShape(QFrame::VLine);
        line_175->setFrameShadow(QFrame::Sunken);

        retranslateUi(button_congee);

        tabWidget_3->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(button_congee);
    } // setupUi

    void retranslateUi(QDialog *button_congee)
    {
        button_congee->setWindowTitle(QApplication::translate("button_congee", "Dialog", Q_NULLPTR));
        pushButton_7->setText(QApplication::translate("button_congee", "Ajouter", Q_NULLPTR));
        label_35->setText(QApplication::translate("button_congee", "Nom", Q_NULLPTR));
        label_36->setText(QApplication::translate("button_congee", "Nbre d'abscence", Q_NULLPTR));
        label_39->setText(QApplication::translate("button_congee", "Prenom", Q_NULLPTR));
        label_42->setText(QString());
        pushButton_15->setText(QApplication::translate("button_congee", "Ajouter", Q_NULLPTR));
        label_7->setText(QString());
        lineEdit_27->setText(QString());
        label_43->setText(QApplication::translate("button_congee", "validation de congee", Q_NULLPTR));
        label_44->setText(QApplication::translate("button_congee", "ID", Q_NULLPTR));
        label_3->setText(QString());
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_8), QApplication::translate("button_congee", "Ajout", Q_NULLPTR));
        pushButton_8->setText(QApplication::translate("button_congee", "Modifier", Q_NULLPTR));
        pushButton_9->setText(QApplication::translate("button_congee", "supprimer", Q_NULLPTR));
        label_45->setText(QApplication::translate("button_congee", "ID", Q_NULLPTR));
        label_46->setText(QApplication::translate("button_congee", "validation de congee", Q_NULLPTR));
        label_47->setText(QApplication::translate("button_congee", "Nom", Q_NULLPTR));
        pushButton_16->setText(QApplication::translate("button_congee", "tri", Q_NULLPTR));
        pushButton_17->setText(QApplication::translate("button_congee", "chercher", Q_NULLPTR));
        pushButton_18->setText(QApplication::translate("button_congee", "Modifier", Q_NULLPTR));
        label_49->setText(QString());
        label_4->setText(QString());
        label_50->setText(QString());
        label_51->setText(QApplication::translate("button_congee", "ID", Q_NULLPTR));
        label_52->setText(QString());
        label_53->setText(QApplication::translate("button_congee", "Prenom", Q_NULLPTR));
        label_54->setText(QApplication::translate("button_congee", "Nbre d'abscence", Q_NULLPTR));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_9), QApplication::translate("button_congee", "Modifier", Q_NULLPTR));
        msg_2->setPlaceholderText(QApplication::translate("button_congee", "type your message here ...", Q_NULLPTR));
        rcpt_2->setPlaceholderText(QApplication::translate("button_congee", "recipient", Q_NULLPTR));
        file_2->setPlaceholderText(QApplication::translate("button_congee", "attachement here", Q_NULLPTR));
        sendBtn_2->setText(QApplication::translate("button_congee", "Send", Q_NULLPTR));
        subject_2->setPlaceholderText(QApplication::translate("button_congee", "subject", Q_NULLPTR));
        mail_pass_2->setPlaceholderText(QApplication::translate("button_congee", "your mail password", Q_NULLPTR));
        browseBtn_2->setText(QApplication::translate("button_congee", "browse", Q_NULLPTR));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_10), QApplication::translate("button_congee", "EMail", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class button_congee: public Ui_button_congee {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_BUTTON_CONGEE_H
