/********************************************************************************
** Form generated from reading UI file 'button_pointage.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_BUTTON_POINTAGE_H
#define UI_BUTTON_POINTAGE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_button_pointage
{
public:
    QTabWidget *tabWidget;
    QWidget *tab;
    QLineEdit *lineEdit;
    QLineEdit *lineEdit_2;
    QLineEdit *lineEdit_3;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_5;
    QLineEdit *lineEdit_6;
    QLineEdit *lineEdit_19;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QLabel *label_3;
    QLabel *label_4;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QFrame *line_9;
    QFrame *line_10;
    QFrame *line_11;
    QFrame *line_14;
    QFrame *line_15;
    QFrame *line_16;
    QFrame *line_17;
    QFrame *line_18;
    QFrame *line_19;
    QFrame *line_20;
    QFrame *line_21;
    QFrame *line_22;
    QFrame *line_23;
    QFrame *line_24;
    QFrame *line_25;
    QFrame *line_26;
    QFrame *line_29;
    QFrame *line_30;
    QFrame *line_31;
    QFrame *line_32;
    QLabel *label_5;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QPushButton *pushButton_9;
    QWidget *tab_2;
    QTableView *tableView;
    QLineEdit *lineEdit_13;
    QLineEdit *lineEdit_14;
    QLineEdit *lineEdit_15;
    QLineEdit *lineEdit_16;
    QLineEdit *lineEdit_17;
    QLineEdit *lineEdit_18;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_7;
    QFrame *line_33;
    QFrame *line_34;
    QFrame *line_35;
    QFrame *line_36;
    QFrame *line_37;
    QFrame *line_38;
    QFrame *line_39;
    QFrame *line_40;
    QFrame *line_41;
    QFrame *line_42;
    QFrame *line_43;
    QFrame *line_44;
    QFrame *line_45;
    QFrame *line_46;
    QFrame *line_47;
    QFrame *line_48;
    QFrame *line_49;
    QFrame *line_50;
    QFrame *line_51;
    QFrame *line_52;
    QFrame *line_53;
    QFrame *line_54;
    QFrame *line_55;
    QFrame *line_56;
    QFrame *line_57;
    QFrame *line_58;
    QFrame *line_59;
    QFrame *line_60;
    QFrame *line_61;
    QFrame *line_62;
    QFrame *line_63;
    QFrame *line_64;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLineEdit *lineEdit_20;
    QPushButton *pushButton_8;
    QPushButton *pushButton_10;
    QFrame *line_97;
    QFrame *line_98;
    QFrame *line_99;
    QFrame *line_100;
    QLabel *label_35;
    QLabel *label_39;
    QPushButton *pushButton_15;
    QTextEdit *textEdit;
    QFrame *line_127;

    void setupUi(QDialog *button_pointage)
    {
        if (button_pointage->objectName().isEmpty())
            button_pointage->setObjectName(QStringLiteral("button_pointage"));
        button_pointage->resize(1069, 616);
        tabWidget = new QTabWidget(button_pointage);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(0, 0, 1071, 641));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        lineEdit = new QLineEdit(tab);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(200, 150, 121, 31));
        QFont font;
        font.setFamily(QStringLiteral("Bahnschrift"));
        font.setPointSize(10);
        lineEdit->setFont(font);
        lineEdit_2 = new QLineEdit(tab);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(200, 270, 121, 31));
        lineEdit_2->setFont(font);
        lineEdit_3 = new QLineEdit(tab);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(200, 360, 121, 31));
        lineEdit_3->setFont(font);
        lineEdit_3->setReadOnly(true);
        lineEdit_4 = new QLineEdit(tab);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(200, 460, 121, 31));
        lineEdit_4->setFont(font);
        lineEdit_4->setReadOnly(true);
        lineEdit_5 = new QLineEdit(tab);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(540, 180, 211, 31));
        lineEdit_5->setFont(font);
        lineEdit_5->setReadOnly(true);
        lineEdit_6 = new QLineEdit(tab);
        lineEdit_6->setObjectName(QStringLiteral("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(540, 290, 121, 31));
        lineEdit_6->setFont(font);
        lineEdit_19 = new QLineEdit(tab);
        lineEdit_19->setObjectName(QStringLiteral("lineEdit_19"));
        lineEdit_19->setGeometry(QRect(860, 280, 151, 41));
        QFont font1;
        font1.setFamily(QStringLiteral("Bahnschrift"));
        font1.setPointSize(20);
        lineEdit_19->setFont(font1);
        line = new QFrame(tab);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(310, 50, 481, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(tab);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(40, 540, 761, 20));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(tab);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(790, 60, 20, 491));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(tab);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(40, 40, 20, 471));
        line_4->setFrameShape(QFrame::VLine);
        line_4->setFrameShadow(QFrame::Sunken);
        label_3 = new QLabel(tab);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(50, 20, 71, 71));
        label_4 = new QLabel(tab);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(830, 220, 61, 61));
        line_5 = new QFrame(tab);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(190, 180, 141, 20));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(tab);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(300, 250, 31, 20));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(tab);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(190, 300, 141, 20));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(tab);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(300, 340, 31, 20));
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(tab);
        line_9->setObjectName(QStringLiteral("line_9"));
        line_9->setGeometry(QRect(190, 390, 141, 20));
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(tab);
        line_10->setObjectName(QStringLiteral("line_10"));
        line_10->setGeometry(QRect(300, 440, 31, 20));
        line_10->setFrameShape(QFrame::HLine);
        line_10->setFrameShadow(QFrame::Sunken);
        line_11 = new QFrame(tab);
        line_11->setObjectName(QStringLiteral("line_11"));
        line_11->setGeometry(QRect(190, 490, 141, 20));
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        line_14 = new QFrame(tab);
        line_14->setObjectName(QStringLiteral("line_14"));
        line_14->setGeometry(QRect(530, 320, 141, 20));
        line_14->setFrameShape(QFrame::HLine);
        line_14->setFrameShadow(QFrame::Sunken);
        line_15 = new QFrame(tab);
        line_15->setObjectName(QStringLiteral("line_15"));
        line_15->setGeometry(QRect(640, 270, 31, 20));
        line_15->setFrameShape(QFrame::HLine);
        line_15->setFrameShadow(QFrame::Sunken);
        line_16 = new QFrame(tab);
        line_16->setObjectName(QStringLiteral("line_16"));
        line_16->setGeometry(QRect(530, 210, 241, 20));
        line_16->setFrameShape(QFrame::HLine);
        line_16->setFrameShadow(QFrame::Sunken);
        line_17 = new QFrame(tab);
        line_17->setObjectName(QStringLiteral("line_17"));
        line_17->setGeometry(QRect(640, 160, 131, 20));
        line_17->setFrameShape(QFrame::HLine);
        line_17->setFrameShadow(QFrame::Sunken);
        line_18 = new QFrame(tab);
        line_18->setObjectName(QStringLiteral("line_18"));
        line_18->setGeometry(QRect(300, 130, 31, 20));
        line_18->setFrameShape(QFrame::HLine);
        line_18->setFrameShadow(QFrame::Sunken);
        line_19 = new QFrame(tab);
        line_19->setObjectName(QStringLiteral("line_19"));
        line_19->setGeometry(QRect(320, 140, 20, 51));
        line_19->setFrameShape(QFrame::VLine);
        line_19->setFrameShadow(QFrame::Sunken);
        line_20 = new QFrame(tab);
        line_20->setObjectName(QStringLiteral("line_20"));
        line_20->setGeometry(QRect(180, 140, 20, 51));
        line_20->setFrameShape(QFrame::VLine);
        line_20->setFrameShadow(QFrame::Sunken);
        line_21 = new QFrame(tab);
        line_21->setObjectName(QStringLiteral("line_21"));
        line_21->setGeometry(QRect(320, 260, 20, 51));
        line_21->setFrameShape(QFrame::VLine);
        line_21->setFrameShadow(QFrame::Sunken);
        line_22 = new QFrame(tab);
        line_22->setObjectName(QStringLiteral("line_22"));
        line_22->setGeometry(QRect(180, 260, 20, 51));
        line_22->setFrameShape(QFrame::VLine);
        line_22->setFrameShadow(QFrame::Sunken);
        line_23 = new QFrame(tab);
        line_23->setObjectName(QStringLiteral("line_23"));
        line_23->setGeometry(QRect(320, 350, 20, 51));
        line_23->setFrameShape(QFrame::VLine);
        line_23->setFrameShadow(QFrame::Sunken);
        line_24 = new QFrame(tab);
        line_24->setObjectName(QStringLiteral("line_24"));
        line_24->setGeometry(QRect(180, 350, 20, 51));
        line_24->setFrameShape(QFrame::VLine);
        line_24->setFrameShadow(QFrame::Sunken);
        line_25 = new QFrame(tab);
        line_25->setObjectName(QStringLiteral("line_25"));
        line_25->setGeometry(QRect(320, 450, 20, 51));
        line_25->setFrameShape(QFrame::VLine);
        line_25->setFrameShadow(QFrame::Sunken);
        line_26 = new QFrame(tab);
        line_26->setObjectName(QStringLiteral("line_26"));
        line_26->setGeometry(QRect(180, 450, 20, 51));
        line_26->setFrameShape(QFrame::VLine);
        line_26->setFrameShadow(QFrame::Sunken);
        line_29 = new QFrame(tab);
        line_29->setObjectName(QStringLiteral("line_29"));
        line_29->setGeometry(QRect(660, 280, 20, 51));
        line_29->setFrameShape(QFrame::VLine);
        line_29->setFrameShadow(QFrame::Sunken);
        line_30 = new QFrame(tab);
        line_30->setObjectName(QStringLiteral("line_30"));
        line_30->setGeometry(QRect(520, 280, 20, 51));
        line_30->setFrameShape(QFrame::VLine);
        line_30->setFrameShadow(QFrame::Sunken);
        line_31 = new QFrame(tab);
        line_31->setObjectName(QStringLiteral("line_31"));
        line_31->setGeometry(QRect(520, 170, 20, 51));
        line_31->setFrameShape(QFrame::VLine);
        line_31->setFrameShadow(QFrame::Sunken);
        line_32 = new QFrame(tab);
        line_32->setObjectName(QStringLiteral("line_32"));
        line_32->setGeometry(QRect(760, 170, 20, 51));
        line_32->setFrameShape(QFrame::VLine);
        line_32->setFrameShadow(QFrame::Sunken);
        label_5 = new QLabel(tab);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(0, 0, 1091, 661));
        label_7 = new QLabel(tab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(190, 120, 71, 21));
        QFont font2;
        font2.setFamily(QStringLiteral("Bahnschrift"));
        font2.setPointSize(14);
        label_7->setFont(font2);
        label_8 = new QLabel(tab);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(190, 240, 71, 21));
        label_8->setFont(font2);
        label_9 = new QLabel(tab);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(190, 330, 121, 20));
        label_9->setFont(font2);
        label_10 = new QLabel(tab);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(190, 430, 121, 21));
        label_10->setFont(font2);
        label_11 = new QLabel(tab);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(530, 140, 101, 31));
        label_11->setFont(font2);
        label_12 = new QLabel(tab);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(530, 260, 51, 21));
        label_12->setFont(font2);
        pushButton_9 = new QPushButton(tab);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(90, 20, 211, 81));
        pushButton_9->setFont(font1);
        tabWidget->addTab(tab, QString());
        label_5->raise();
        pushButton_9->raise();
        lineEdit->raise();
        lineEdit_2->raise();
        lineEdit_3->raise();
        lineEdit_4->raise();
        lineEdit_5->raise();
        lineEdit_6->raise();
        lineEdit_19->raise();
        line->raise();
        line_2->raise();
        line_3->raise();
        line_4->raise();
        label_4->raise();
        line_5->raise();
        line_6->raise();
        line_7->raise();
        line_8->raise();
        line_9->raise();
        line_10->raise();
        line_11->raise();
        line_14->raise();
        line_15->raise();
        line_16->raise();
        line_17->raise();
        line_18->raise();
        line_19->raise();
        line_20->raise();
        line_21->raise();
        line_22->raise();
        line_23->raise();
        line_24->raise();
        line_25->raise();
        line_26->raise();
        line_29->raise();
        line_30->raise();
        line_31->raise();
        line_32->raise();
        label_7->raise();
        label_8->raise();
        label_9->raise();
        label_10->raise();
        label_11->raise();
        label_12->raise();
        label_3->raise();
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        tableView = new QTableView(tab_2);
        tableView->setObjectName(QStringLiteral("tableView"));
        tableView->setGeometry(QRect(680, 130, 351, 301));
        lineEdit_13 = new QLineEdit(tab_2);
        lineEdit_13->setObjectName(QStringLiteral("lineEdit_13"));
        lineEdit_13->setGeometry(QRect(100, 100, 121, 31));
        lineEdit_13->setFont(font);
        lineEdit_14 = new QLineEdit(tab_2);
        lineEdit_14->setObjectName(QStringLiteral("lineEdit_14"));
        lineEdit_14->setGeometry(QRect(100, 220, 121, 31));
        lineEdit_14->setFont(font);
        lineEdit_15 = new QLineEdit(tab_2);
        lineEdit_15->setObjectName(QStringLiteral("lineEdit_15"));
        lineEdit_15->setGeometry(QRect(100, 330, 121, 31));
        lineEdit_15->setFont(font);
        lineEdit_15->setReadOnly(true);
        lineEdit_16 = new QLineEdit(tab_2);
        lineEdit_16->setObjectName(QStringLiteral("lineEdit_16"));
        lineEdit_16->setGeometry(QRect(100, 450, 121, 31));
        lineEdit_16->setFont(font);
        lineEdit_16->setReadOnly(true);
        lineEdit_17 = new QLineEdit(tab_2);
        lineEdit_17->setObjectName(QStringLiteral("lineEdit_17"));
        lineEdit_17->setGeometry(QRect(350, 210, 221, 31));
        lineEdit_17->setFont(font);
        lineEdit_17->setReadOnly(true);
        lineEdit_18 = new QLineEdit(tab_2);
        lineEdit_18->setObjectName(QStringLiteral("lineEdit_18"));
        lineEdit_18->setGeometry(QRect(350, 90, 111, 31));
        lineEdit_18->setFont(font);
        pushButton_2 = new QPushButton(tab_2);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(380, 320, 181, 71));
        pushButton_2->setFont(font2);
        pushButton_3 = new QPushButton(tab_2);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(380, 420, 181, 71));
        QFont font3;
        font3.setFamily(QStringLiteral("Bahnschrift"));
        font3.setPointSize(12);
        pushButton_3->setFont(font3);
        pushButton_7 = new QPushButton(tab_2);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(900, 490, 131, 51));
        QFont font4;
        font4.setFamily(QStringLiteral("Bahnschrift"));
        font4.setPointSize(8);
        pushButton_7->setFont(font4);
        line_33 = new QFrame(tab_2);
        line_33->setObjectName(QStringLiteral("line_33"));
        line_33->setGeometry(QRect(260, 30, 361, 20));
        line_33->setFrameShape(QFrame::HLine);
        line_33->setFrameShadow(QFrame::Sunken);
        line_34 = new QFrame(tab_2);
        line_34->setObjectName(QStringLiteral("line_34"));
        line_34->setGeometry(QRect(0, 540, 621, 20));
        line_34->setFrameShape(QFrame::HLine);
        line_34->setFrameShadow(QFrame::Sunken);
        line_35 = new QFrame(tab_2);
        line_35->setObjectName(QStringLiteral("line_35"));
        line_35->setGeometry(QRect(0, 40, 16, 511));
        line_35->setFrameShape(QFrame::VLine);
        line_35->setFrameShadow(QFrame::Sunken);
        line_36 = new QFrame(tab_2);
        line_36->setObjectName(QStringLiteral("line_36"));
        line_36->setGeometry(QRect(610, 40, 16, 511));
        line_36->setFrameShape(QFrame::VLine);
        line_36->setFrameShadow(QFrame::Sunken);
        line_37 = new QFrame(tab_2);
        line_37->setObjectName(QStringLiteral("line_37"));
        line_37->setGeometry(QRect(670, 430, 371, 20));
        line_37->setFrameShape(QFrame::HLine);
        line_37->setFrameShadow(QFrame::Sunken);
        line_38 = new QFrame(tab_2);
        line_38->setObjectName(QStringLiteral("line_38"));
        line_38->setGeometry(QRect(670, 110, 371, 20));
        line_38->setFrameShape(QFrame::HLine);
        line_38->setFrameShadow(QFrame::Sunken);
        line_39 = new QFrame(tab_2);
        line_39->setObjectName(QStringLiteral("line_39"));
        line_39->setGeometry(QRect(660, 120, 20, 321));
        line_39->setFrameShape(QFrame::VLine);
        line_39->setFrameShadow(QFrame::Sunken);
        line_40 = new QFrame(tab_2);
        line_40->setObjectName(QStringLiteral("line_40"));
        line_40->setGeometry(QRect(1030, 120, 20, 321));
        line_40->setFrameShape(QFrame::VLine);
        line_40->setFrameShadow(QFrame::Sunken);
        line_41 = new QFrame(tab_2);
        line_41->setObjectName(QStringLiteral("line_41"));
        line_41->setGeometry(QRect(90, 130, 141, 16));
        line_41->setFrameShape(QFrame::HLine);
        line_41->setFrameShadow(QFrame::Sunken);
        line_42 = new QFrame(tab_2);
        line_42->setObjectName(QStringLiteral("line_42"));
        line_42->setGeometry(QRect(200, 80, 31, 20));
        line_42->setFrameShape(QFrame::HLine);
        line_42->setFrameShadow(QFrame::Sunken);
        line_43 = new QFrame(tab_2);
        line_43->setObjectName(QStringLiteral("line_43"));
        line_43->setGeometry(QRect(200, 200, 31, 20));
        line_43->setFrameShape(QFrame::HLine);
        line_43->setFrameShadow(QFrame::Sunken);
        line_44 = new QFrame(tab_2);
        line_44->setObjectName(QStringLiteral("line_44"));
        line_44->setGeometry(QRect(90, 250, 141, 16));
        line_44->setFrameShape(QFrame::HLine);
        line_44->setFrameShadow(QFrame::Sunken);
        line_45 = new QFrame(tab_2);
        line_45->setObjectName(QStringLiteral("line_45"));
        line_45->setGeometry(QRect(340, 240, 241, 16));
        line_45->setFrameShape(QFrame::HLine);
        line_45->setFrameShadow(QFrame::Sunken);
        line_46 = new QFrame(tab_2);
        line_46->setObjectName(QStringLiteral("line_46"));
        line_46->setGeometry(QRect(90, 360, 141, 16));
        line_46->setFrameShape(QFrame::HLine);
        line_46->setFrameShadow(QFrame::Sunken);
        line_47 = new QFrame(tab_2);
        line_47->setObjectName(QStringLiteral("line_47"));
        line_47->setGeometry(QRect(200, 310, 31, 20));
        line_47->setFrameShape(QFrame::HLine);
        line_47->setFrameShadow(QFrame::Sunken);
        line_48 = new QFrame(tab_2);
        line_48->setObjectName(QStringLiteral("line_48"));
        line_48->setGeometry(QRect(190, 430, 41, 20));
        line_48->setFrameShape(QFrame::HLine);
        line_48->setFrameShadow(QFrame::Sunken);
        line_49 = new QFrame(tab_2);
        line_49->setObjectName(QStringLiteral("line_49"));
        line_49->setGeometry(QRect(90, 480, 141, 16));
        line_49->setFrameShape(QFrame::HLine);
        line_49->setFrameShadow(QFrame::Sunken);
        line_50 = new QFrame(tab_2);
        line_50->setObjectName(QStringLiteral("line_50"));
        line_50->setGeometry(QRect(520, 190, 61, 20));
        line_50->setFrameShape(QFrame::HLine);
        line_50->setFrameShadow(QFrame::Sunken);
        line_51 = new QFrame(tab_2);
        line_51->setObjectName(QStringLiteral("line_51"));
        line_51->setGeometry(QRect(340, 120, 141, 16));
        line_51->setFrameShape(QFrame::HLine);
        line_51->setFrameShadow(QFrame::Sunken);
        line_52 = new QFrame(tab_2);
        line_52->setObjectName(QStringLiteral("line_52"));
        line_52->setGeometry(QRect(450, 70, 31, 20));
        line_52->setFrameShape(QFrame::HLine);
        line_52->setFrameShadow(QFrame::Sunken);
        line_53 = new QFrame(tab_2);
        line_53->setObjectName(QStringLiteral("line_53"));
        line_53->setGeometry(QRect(220, 440, 20, 51));
        line_53->setFrameShape(QFrame::VLine);
        line_53->setFrameShadow(QFrame::Sunken);
        line_54 = new QFrame(tab_2);
        line_54->setObjectName(QStringLiteral("line_54"));
        line_54->setGeometry(QRect(80, 440, 20, 51));
        line_54->setFrameShape(QFrame::VLine);
        line_54->setFrameShadow(QFrame::Sunken);
        line_55 = new QFrame(tab_2);
        line_55->setObjectName(QStringLiteral("line_55"));
        line_55->setGeometry(QRect(80, 320, 20, 51));
        line_55->setFrameShape(QFrame::VLine);
        line_55->setFrameShadow(QFrame::Sunken);
        line_56 = new QFrame(tab_2);
        line_56->setObjectName(QStringLiteral("line_56"));
        line_56->setGeometry(QRect(220, 320, 20, 51));
        line_56->setFrameShape(QFrame::VLine);
        line_56->setFrameShadow(QFrame::Sunken);
        line_57 = new QFrame(tab_2);
        line_57->setObjectName(QStringLiteral("line_57"));
        line_57->setGeometry(QRect(220, 210, 20, 51));
        line_57->setFrameShape(QFrame::VLine);
        line_57->setFrameShadow(QFrame::Sunken);
        line_58 = new QFrame(tab_2);
        line_58->setObjectName(QStringLiteral("line_58"));
        line_58->setGeometry(QRect(80, 210, 20, 51));
        line_58->setFrameShape(QFrame::VLine);
        line_58->setFrameShadow(QFrame::Sunken);
        line_59 = new QFrame(tab_2);
        line_59->setObjectName(QStringLiteral("line_59"));
        line_59->setGeometry(QRect(80, 90, 20, 51));
        line_59->setFrameShape(QFrame::VLine);
        line_59->setFrameShadow(QFrame::Sunken);
        line_60 = new QFrame(tab_2);
        line_60->setObjectName(QStringLiteral("line_60"));
        line_60->setGeometry(QRect(220, 90, 20, 51));
        line_60->setFrameShape(QFrame::VLine);
        line_60->setFrameShadow(QFrame::Sunken);
        line_61 = new QFrame(tab_2);
        line_61->setObjectName(QStringLiteral("line_61"));
        line_61->setGeometry(QRect(330, 80, 20, 51));
        line_61->setFrameShape(QFrame::VLine);
        line_61->setFrameShadow(QFrame::Sunken);
        line_62 = new QFrame(tab_2);
        line_62->setObjectName(QStringLiteral("line_62"));
        line_62->setGeometry(QRect(470, 80, 20, 51));
        line_62->setFrameShape(QFrame::VLine);
        line_62->setFrameShadow(QFrame::Sunken);
        line_63 = new QFrame(tab_2);
        line_63->setObjectName(QStringLiteral("line_63"));
        line_63->setGeometry(QRect(570, 200, 20, 51));
        line_63->setFrameShape(QFrame::VLine);
        line_63->setFrameShadow(QFrame::Sunken);
        line_64 = new QFrame(tab_2);
        line_64->setObjectName(QStringLiteral("line_64"));
        line_64->setGeometry(QRect(330, 200, 20, 51));
        line_64->setFrameShape(QFrame::VLine);
        line_64->setFrameShadow(QFrame::Sunken);
        label_13 = new QLabel(tab_2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(90, 70, 61, 21));
        label_13->setFont(font2);
        label_14 = new QLabel(tab_2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(90, 190, 71, 21));
        label_14->setFont(font2);
        label_15 = new QLabel(tab_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(90, 300, 121, 20));
        label_15->setFont(font2);
        label_16 = new QLabel(tab_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(90, 420, 121, 21));
        label_16->setFont(font2);
        label_17 = new QLabel(tab_2);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(340, 170, 111, 31));
        label_17->setFont(font2);
        label_18 = new QLabel(tab_2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(340, 60, 91, 21));
        label_18->setFont(font2);
        label_19 = new QLabel(tab_2);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(20, 0, 61, 61));
        label_20 = new QLabel(tab_2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(340, 320, 61, 61));
        label_21 = new QLabel(tab_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(340, 420, 61, 61));
        label_22 = new QLabel(tab_2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(-10, -50, 1091, 671));
        lineEdit_20 = new QLineEdit(tab_2);
        lineEdit_20->setObjectName(QStringLiteral("lineEdit_20"));
        lineEdit_20->setGeometry(QRect(690, 50, 111, 31));
        lineEdit_20->setFont(font);
        pushButton_8 = new QPushButton(tab_2);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(870, 30, 181, 61));
        QFont font5;
        font5.setFamily(QStringLiteral("Bahnschrift"));
        font5.setPointSize(6);
        pushButton_8->setFont(font5);
        pushButton_10 = new QPushButton(tab_2);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(50, 0, 201, 71));
        pushButton_10->setFont(font1);
        line_97 = new QFrame(tab_2);
        line_97->setObjectName(QStringLiteral("line_97"));
        line_97->setGeometry(QRect(680, 80, 131, 20));
        line_97->setFrameShape(QFrame::HLine);
        line_97->setFrameShadow(QFrame::Sunken);
        line_98 = new QFrame(tab_2);
        line_98->setObjectName(QStringLiteral("line_98"));
        line_98->setGeometry(QRect(780, 30, 31, 20));
        line_98->setFrameShape(QFrame::HLine);
        line_98->setFrameShadow(QFrame::Sunken);
        line_99 = new QFrame(tab_2);
        line_99->setObjectName(QStringLiteral("line_99"));
        line_99->setGeometry(QRect(670, 40, 20, 51));
        line_99->setFrameShape(QFrame::VLine);
        line_99->setFrameShadow(QFrame::Sunken);
        line_100 = new QFrame(tab_2);
        line_100->setObjectName(QStringLiteral("line_100"));
        line_100->setGeometry(QRect(800, 40, 20, 51));
        line_100->setFrameShape(QFrame::VLine);
        line_100->setFrameShadow(QFrame::Sunken);
        label_35 = new QLabel(tab_2);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(680, 20, 91, 21));
        label_35->setFont(font2);
        label_39 = new QLabel(tab_2);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(840, 30, 51, 51));
        pushButton_15 = new QPushButton(tab_2);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(700, 490, 141, 51));
        textEdit = new QTextEdit(tab_2);
        textEdit->setObjectName(QStringLiteral("textEdit"));
        textEdit->setGeometry(QRect(630, 490, 61, 51));
        tabWidget->addTab(tab_2, QString());
        label_22->raise();
        tableView->raise();
        lineEdit_13->raise();
        lineEdit_14->raise();
        lineEdit_15->raise();
        lineEdit_16->raise();
        lineEdit_17->raise();
        lineEdit_18->raise();
        pushButton_2->raise();
        pushButton_3->raise();
        pushButton_7->raise();
        line_33->raise();
        line_34->raise();
        line_35->raise();
        line_36->raise();
        line_37->raise();
        line_38->raise();
        line_39->raise();
        line_40->raise();
        line_41->raise();
        line_42->raise();
        line_43->raise();
        line_44->raise();
        line_45->raise();
        line_46->raise();
        line_47->raise();
        line_48->raise();
        line_49->raise();
        line_50->raise();
        line_51->raise();
        line_52->raise();
        line_53->raise();
        line_54->raise();
        line_55->raise();
        line_56->raise();
        line_57->raise();
        line_58->raise();
        line_59->raise();
        line_60->raise();
        line_61->raise();
        line_62->raise();
        line_63->raise();
        line_64->raise();
        label_13->raise();
        label_14->raise();
        label_15->raise();
        label_16->raise();
        label_17->raise();
        label_18->raise();
        label_20->raise();
        label_21->raise();
        lineEdit_20->raise();
        pushButton_8->raise();
        pushButton_10->raise();
        label_19->raise();
        line_97->raise();
        line_98->raise();
        line_99->raise();
        line_100->raise();
        label_35->raise();
        label_39->raise();
        pushButton_15->raise();
        textEdit->raise();
        line_127 = new QFrame(button_pointage);
        line_127->setObjectName(QStringLiteral("line_127"));
        line_127->setGeometry(QRect(2160, 850, 20, 501));
        line_127->setFrameShape(QFrame::VLine);
        line_127->setFrameShadow(QFrame::Sunken);

        retranslateUi(button_pointage);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(button_pointage);
    } // setupUi

    void retranslateUi(QDialog *button_pointage)
    {
        button_pointage->setWindowTitle(QApplication::translate("button_pointage", "Dialog", Q_NULLPTR));
        lineEdit_19->setText(QString());
        label_3->setText(QString());
        label_4->setText(QString());
        label_5->setText(QString());
        label_7->setText(QApplication::translate("button_pointage", "Nom", Q_NULLPTR));
        label_8->setText(QApplication::translate("button_pointage", "Prenom", Q_NULLPTR));
        label_9->setText(QApplication::translate("button_pointage", "Date d'entree", Q_NULLPTR));
        label_10->setText(QApplication::translate("button_pointage", "Date de sortie", Q_NULLPTR));
        label_11->setText(QApplication::translate("button_pointage", "retard", Q_NULLPTR));
        label_12->setText(QApplication::translate("button_pointage", "ID", Q_NULLPTR));
        pushButton_9->setText(QApplication::translate("button_pointage", "Ajouter", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("button_pointage", "Ajout", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("button_pointage", "modifier", Q_NULLPTR));
        pushButton_3->setText(QApplication::translate("button_pointage", "  supprimer", Q_NULLPTR));
        pushButton_7->setText(QApplication::translate("button_pointage", "tri", Q_NULLPTR));
        label_13->setText(QApplication::translate("button_pointage", "Nom", Q_NULLPTR));
        label_14->setText(QApplication::translate("button_pointage", "Prebom", Q_NULLPTR));
        label_15->setText(QApplication::translate("button_pointage", "Date d' entree", Q_NULLPTR));
        label_16->setText(QApplication::translate("button_pointage", "Date de Sortie", Q_NULLPTR));
        label_17->setText(QApplication::translate("button_pointage", "Retard", Q_NULLPTR));
        label_18->setText(QApplication::translate("button_pointage", "ID", Q_NULLPTR));
        label_19->setText(QString());
        label_20->setText(QString());
        label_21->setText(QString());
        label_22->setText(QString());
        pushButton_8->setText(QApplication::translate("button_pointage", "  Chercher", Q_NULLPTR));
        pushButton_10->setText(QApplication::translate("button_pointage", "Modifier", Q_NULLPTR));
        label_35->setText(QApplication::translate("button_pointage", "ID", Q_NULLPTR));
        label_39->setText(QString());
        pushButton_15->setText(QApplication::translate("button_pointage", "Print", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("button_pointage", "Modifier", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class button_pointage: public Ui_button_pointage {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_BUTTON_POINTAGE_H
